latent: true
model: meta-llama/Llama-3.2-1B 
base_latent_model: 
tokenizer: meta-llama/Llama-3.2-1B
dataset: 
log_dir: eval/logs
eval_name: 
split: valid

freeze_embeddings:
max_new_latents: 
probe_latents:
unembed_latents:
dynamically_stop: 